// Generated by CoffeeScript 1.7.1
describe('list-filter-text', function() {
  beforeEach(function() {
    module('listFilterTextTemplate');
    return module('listFilterText');
  });
  beforeEach(inject(function($compile, $rootScope) {
    this.$compile = $compile;
    this.scope = $rootScope.$new();
    return this.element = angular.element("<list-filter-text\n	param=\"searchText\"\n	size=\"medium\"\n	placeholder=\"Search\"\n></list-filter-text>");
  }));
  beforeEach(function() {
    (this.$compile(this.element))(this.scope);
    return this.scope.$digest();
  });
  return describe('#foo', function() {
    return it('should bar', function() {
      return expect(true).toBe(true);
    });
  });
});
